<!DOCTYPE html>
<html lang ='en' class="">
    <title>VirtualClass360
        </title>
        <head>
            <head>
                <meta charset='utf-8' />
                <meta name='viewport' content='initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width, minimum-scale=1, viewport-fit=cover' />
                <meta name='keywords' content='VirtualClass360, What is Virtual Reality?, About Us,virtualclass360.com, wwww.virtuallclass360.com'/>
                <link rel ="image" href="Class360.jpg" type="image"/>
                <link rel ="image" href="small.jpg" type="image"/>
                <link rel ="image" href="six.jpg" type="image"/>
        </head>
        <body>
            <img src="Class360.jpg"/>
<center>
            <h1>VirtualClass360</h1>  
        <title>VirtualClass360</title> 
           
                <h1>About Us</h1>
                <p> Add text  here... </p>
                <div class ="column"></div>
            <img src="intro.jpg" align="left" />
            <h2><img src="3.jpg"/>Virtual Reality</h2>
            <p>
                Virtual Reality (VR) is the latest in the world of Education, a three dimensional (3D) computer generated Education using a head-mounted display.
                VR is  bringing efficient learning experience at an affordable price by providing virtually a ‘real world’  experience of the concepts of science, history and various subjects.
                From real estate to Military to healthcare, VR learning is formally being introduced since  the science of VR has been found to enhance  knowledge retention during learning. 
                With the smartphone in the hands of the general public, the VR popularity gained momentum for various applications.
            </p>
            <br>
            <br>
            <br>
            <br>
        <div class="column">
        <img src="six.jpg" align ="right"/>

        <div class="column" align ="left"></div>
        <h2>What is Virtual Reality?</h2>
        <p>
            A VR makes a  person feel like he is within the scenario physically and, further, with the movement of head, the world also turns. 
            The display typically splits the image between the left and right eyes, creating a stereoscopic 3D effect with stereo sound and an immersive experience, allowing a person to visualise a virtual world being generated by the computer.  The definition comes from the terms ‘virtual’ and ‘reality’ viz. ‘virtual’ as ‘simulated’ by computer  and ‘reality’ as we experience as humans. 
            Therefore, the term VR can be also defined as ‘near-reality’. 
            In everyday life, we perceive  the world around us through our primary and secondary sensors. 
            This sensory information is processed by our brain to present a rich flow of information from the environment to our brains. 
            Hence, when our senses are fed with similar synthetic information, human perception of reality also changes in response to it. 
            VR presents a version of reality that isn’t really there, but from our perspective perceived as real.

        </p>
    </div>    
<br>
<br>
<br>
    <h2> How is Virtual Reality achieved?</h2>

    <p>
        Today VR is implemented using computer technology, along with a range of systems such as headsets, special gloves etc. 
        These are used to actually stimulate our senses together in order to create the illusion of reality to give us an immersive experience. 
        Humans have nearly  180 degree vision and we are unconsciously aware of peripheral vision. 
        Whenever eyes and the vestibular system (sensory system in the ear that is responsible for providing our brain with information about motion, head position, and spatial orientation) are in conflict, it can cause motion sickness. 
        A good implementation of VR manages to get the combination of hardware, software and sensory synchronicity rightly balanced to achieve sense of balance i.e.  one really feels like they are present in that environment.
        </p>
        <footer>
            <p>
                VR is  the new method of how humans interface with the digital technologies. 
                Immersive films and video games are the primary beneficiaries of VR. 
                The entertainment is a multi-billion dollar industry and are ever keen to develop  novelty to enrich the experience of the audiences. 
                However, VR has applications which too have evolved in Medicine, Sports, Architecture and more importantly in the Education sector. 
                Wherever it is too dangerous, expensive or practically not viable to do something in actual, the VR is the solution.

            </p>
        </footer>
 </center>

          </body>

</html>
